[package]
name = "dot"
version = "0.8.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
clap_complete = "4.5.65"
directories-next = "2"
git-url-parse = "0.6.0"
nuke-eval = { version = "0.5.0", git = "https://github.com/vahanbgs/nuke.git", tag = "0.5.0", features = ["serde"] }
nuke-transpile = { version = "0.5.0", git = "https://github.com/vahanbgs/nuke.git", tag = "0.5.0", features = ["serde"] }
opensesame = "0.1.1"
serde = { version = "1.0.228", features = ["derive"] }
tempfile = "3.24.0"
tielpmet = { version = "0.2.0", git = "https://github.com/vahanbgs/tielpmet.git", tag = "0.2.0" }
toml = "0.9.10"
walkdir = "2.5.0"

[build-dependencies]
clap = { version = "4.5.53", features = ["derive"] }
clap_complete = "4.5.65"
clap_complete_nushell = "4.6.0"
git-url-parse = "0.6.0"
